-- 코드를 입력하세요
SELECT DISTINCT(CAR_ID), 
    CASE 
        WHEN 0 < (SELECT COUNT(*) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE AND CAR_ID = HISTORY.CAR_ID) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
ORDER BY CAR_ID DESC;

# SELECT DISTINCT(CAR_ID)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE START_DATE <= '2022-10-16' AND END_DATE <= '2022-10-16'
# ORDER BY CAR_ID;