-- 코드를 입력하세요
SELECT DISTINCT(CAR_ID),
    CASE
        WHEN 0 < (SELECT COUNT(*) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY IH WHERE START_DATE <= DATE '2022-10-16' AND END_DATE >= DATE '2022-10-16' AND IH.CAR_ID = H.CAR_ID GROUP BY CAR_ID) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ORDER BY CAR_ID DESC;