-- 코드를 입력하세요
SELECT DATE_FORMAT(START_DATE, "%m") AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y%m") >= '202208' 
AND DATE_FORMAT(START_DATE, "%Y%m") <= '202210'
AND CAR_ID IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE_FORMAT(START_DATE, "%Y%m") >= '202208' 
    AND DATE_FORMAT(START_DATE, "%Y%m") <= '202210'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;
