-- 코드를 입력하세요
SELECT DISTINCT(HISTORY.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON HISTORY.CAR_ID = CAR.CAR_ID
WHERE CAR_TYPE = '세단' AND START_DATE > '2022-10-00'
ORDER BY HISTORY.CAR_ID DESC;