-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS FI JOIN FISH_NAME_INFO ON FI.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE LENGTH = (SELECT MAX(LENGTH) 
                FROM FISH_INFO 
                GROUP BY FISH_TYPE 
                HAVING FISH_TYPE=FI.FISH_TYPE)
ORDER BY ID;
